const { Router } = require("express")
const usersRouter = require("./users.routes")
const profissionaisRouter = require("./profissionais.routes")
const avaliaçõesRouter = require("./avaliações.routes")
const horáriosRouter = require("./horários.routes")
const horáriosUserRouter = require("./horáriosUser.routes")
const mensagensRouter = require("./mensagens.routes")
const favoritesRouter = require("./favorites.routes")
const sessionsRouter = require("./sessions.routes")
const sessionsProfRouter = require("./sessionsProf.routes")
const searchRouter = require("./search.routes")

const routes = Router()

routes.use("/users", usersRouter)
routes.use("/profissionais", profissionaisRouter)
routes.use("/mensagens", mensagensRouter)
routes.use("/favorites", favoritesRouter)
routes.use("/sessions", sessionsRouter)
routes.use("/sessionsprof", sessionsProfRouter)
routes.use("/search", searchRouter)
routes.use("/avaliacoes", avaliaçõesRouter)
routes.use("/horarios", horáriosRouter)
routes.use("/horariosuser", horáriosUserRouter)

module.exports = routes