const { Router } = require("express")
const usersRouter = require("./users.routes")
const profissionaisRouter = require("./profissionais.routes")
const avaliaçõesRouter = require("./avaliações.routes")
const horáriosSegundaRouter = require("./horáriosSegunda.routes")
const horáriosTerçaRouter = require("./horáriosTerça.routes")
const horáriosSegundaUserRouter = require("./horáriosSegundaUser.routes")
const horáriosTerçaUserRouter = require("./horáriosTerçaUser.routes")
const horáriosQuintaUserRouter = require("./horáriosQuintaUser.routes")
const horáriosSextaUserRouter = require("./horáriosSextaUser.routes")
const horáriosSábadoUserRouter = require("./horáriosSábadoUser.routes")
const horáriosQuartaRouter = require("./horáriosQuarta.routes")
const horáriosQuartaUserRouter = require("./horáriosQuartaUser.routes")
const horáriosQuintaRouter = require("./horáriosQuinta.routes")
const horáriosSextaRouter = require("./horáriosSexta.routes")
const horáriosSábadoRouter = require("./horáriosSábado.routes")
const mensagensRouter = require("./mensagens.routes")
const favoritesRouter = require("./favorites.routes")
const sessionsRouter = require("./sessions.routes")
const sessionsProfRouter = require("./sessionsProf.routes")
const searchRouter = require("./search.routes")

const routes = Router()

routes.use("/users", usersRouter)
routes.use("/profissionais", profissionaisRouter)
routes.use("/mensagens", mensagensRouter)
routes.use("/favorites", favoritesRouter)
routes.use("/sessions", sessionsRouter)
routes.use("/sessionsprof", sessionsProfRouter)
routes.use("/search", searchRouter)
routes.use("/avaliacoes", avaliaçõesRouter)
routes.use("/segunda", horáriosSegundaRouter)
routes.use("/terca", horáriosTerçaRouter)
routes.use("/tercauser", horáriosTerçaUserRouter)
routes.use("/quarta", horáriosQuartaRouter)
routes.use("/quartauser", horáriosQuartaUserRouter)
routes.use("/segundauser", horáriosSegundaUserRouter)
routes.use("/quintauser", horáriosQuintaUserRouter)
routes.use("/sextauser", horáriosSextaUserRouter)
routes.use("/sabadouser", horáriosSábadoUserRouter)
routes.use("/quinta", horáriosQuintaRouter)
routes.use("/sexta", horáriosSextaRouter)
routes.use("/sabado", horáriosSábadoRouter)


module.exports = routes